name: Pull Request Prefix Check

on:
  pull_request:
    types: [ opened, edited ]

jobs:
  check-prefix:
    name: Check PR Prefix
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == false
    steps:
      - name: Check PR Prefix
        run: |
          set -e
          
          PREFIXES=("major" "breaking" "feat" "feature" "fix" "hotfix" "patch")
          
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_PREFIX=$(echo "${PR_TITLE}" | cut -d ':' -f 1)
          
          echo "PR Title: ${PR_TITLE}"
          echo "Prefix: ${PR_PREFIX}"
          
          if ! [[ " ${PREFIXES[@]} " =~ " ${PR_PREFIX} " ]]; then
            echo "Error: Pull request title must start with one of the following prefixes: ${PREFIXES[*]}" >&2
            exit 1
          fi
