name: Pull Request Prefix Check

on:
  pull_request:
    types: [ opened, edited, synchronize ]

jobs:
  check_prefix:
    runs-on: ubuntu-latest
    steps:
      - name: Check Pull Request Prefix
        uses: ramonsnir/gh-action-pr-title@1.0.0
        with:
          pattern: '^(major|breaking|feat|feature|fix|hotfix):'
          error-message: 'Invalid pull request title. The title must start with one of the following prefixes: major:, breaking:, feat:, feature:, fix:, or hotfix:'
