name: Bump & Publish

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  version_and_publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install Dependencies
        run: npm ci
      - name: Bump Version
        run: |
          VERSION=$(npm version --no-git-tag-version)
          PR_TITLE=$(jq --raw-output .pull_request.title "$GITHUB_EVENT_PATH")
          if [[ "$PR_TITLE" =~ ^major:|^breaking: ]]; then
            npm version major
          elif [[ "$PR_TITLE" =~ ^feat:|^feature: ]]; then
            npm version minor
          elif [[ "$PR_TITLE" =~ ^fix:|^hotfix: ]]; then
            npm version patch
          else
            echo "Error: Pull request title must start with one of the following prefixes: 'major:', 'breaking:', 'feat:', 'feature:', 'fix:', 'hotfix:'"
            exit 1
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
     # - name: Publish to npm
     #   run: npm publish
     #   if: success()
     #   env:
     #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
